Add exception handling for JSON::ParserError
sous-chefs/grafana pull request #155
Opened 2016-12-07 12:29 UTC by ton31337

Add exception handling for JSON::ParserError. Without this exception handling, error is returned on updating resources:

```       ================================================================================
           Error executing action `update` on resource 'grafana_datasource[prometheus]'
           ================================================================================

           JSON::ParserError
           -----------------
           784: unexpected token at '<*api.NormalResponse Value>'
```
After this, everything is fine, all resources including `grafana_datasource`, `grafana_user`, `grafana_dashboard`, `grafana_organization` are working properly as expected.
@gregf

2016-12-07 15:54 UTC, ton31337 commented
ping @gregf @JonathanTron

2017-11-15 20:24 UTC, scopenco requested changes
Thank you for PR! Please leave only `libraries/organization_api.rb` changes and rebase PR.

2017-11-16 06:43 UTC, ton31337 commented
👍

2017-11-16 06:45 UTC, scopenco approved these changes

2017-11-16 06:45 UTC, merged