new attribute node[grafana][restart_on_upgrade]
sous-chefs/grafana pull request #164
Opened 2017-03-16 09:12 UTC by InformatiQ

2017-07-13 07:11 UTC, iksaif commented
ping ?

2017-11-15 20:22 UTC, scopenco requested changes
I think this PR should be merged. @InformatiQ please fix merge conflicts.

2017-11-16 09:01 UTC, InformatiQ commented
fixed merge conflicts

2017-11-16 09:50 UTC, merged

2017-11-16 09:50 UTC, scopenco commented
@InformatiQ Thanks!