Update to grafana 5.3.2
sous-chefs/grafana pull request #203
Opened 2018-10-25 05:21 UTC by eheydrick

Signed-off-by: Eric Heydrick <eheydrick@gmail.com>

### Description

Update to latest grafana release, 5.3.2. Also add testing on Ubuntu 18.04. All tests pass.

### Issues Resolved

None.

### Check List
- [x] All tests pass. See https://github.com/sous-chefs/grafana/blob/master/TESTING.md
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable

2018-10-25 07:14 UTC, kitchen-porter commented
<!--
  2 Errors: Please add labels to this Pull...
  0 Warnings
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          2 Errors
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please add labels to this Pull Request</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a <a href="https://github.com/sous-chefs/grafana/blob/master/CHANGELOG.md">CHANGELOG</a> entry.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2018-10-25 07:19 UTC, damacus commented on .kitchen.dokken.yml
> +
Whilst you're here you can probably remove Ubuntu 14.04

2018-10-25 07:21 UTC, damacus requested changes
Remove Ubuntu 14.04 from dokken?

2018-10-25 07:22 UTC, damacus commented
Hah Danger actually picked up something useful, you also probably need a CHANGELOG entry for the version upgrade.

2018-10-26 21:54 UTC, eheydrick commented
I'll nuke 14.04 and add a CHANGELOG entry, Where should it go? An Unreleased section at the top?

2018-11-26 23:43 UTC, Xorima commented
@eheydrick did you get a chance to add the Change log and remove 14.04?

2018-11-26 23:59 UTC, eheydrick commented
Oh apologies, I'll add that tonight.

2018-11-27 08:08 UTC, eheydrick commented
Ready for final review. I also bumped to the latest release, 5.3.4. There's a security issue fixed in 5.3.3 so good to be current.

2018-11-27 08:12 UTC, xorima approved these changes
Looks good to me, thanks

2018-11-27 13:57 UTC, damacus approved these changes

2018-11-27 13:57 UTC, merged