Config redesign
sous-chefs/grafana pull request #218
Opened 2019-01-06 18:34 UTC by Xorima

### Description

Enables us to manage the configuration file using resources

### Issues Resolved

#213 

### Check List
- [ ] All tests pass. See https://github.com/sous-chefs/grafana/blob/master/TESTING.md
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable

2019-01-06 18:34 UTC, kitchen-porter commented
<!--
  0 Errors
  1 Warning: This is a big Pull Request.
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This is a big Pull Request.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2019-01-07 01:52 UTC, JohnRoesler submitted a review, later dismissed
Huge PR! Looking good to me, pending the failing circle tests

2019-01-07 20:07 UTC, damacus commented on .circleci/config.yml
> +          suite: install
If this is the default set of tests, we can probably just use default for simplicity.

"Hey this is the default setup, and it's mostly covered in this suite"

2019-01-07 20:08 UTC, damacus commented on Berksfile
>    cookbook 'curl'
These two can get removed, they should be in the metadata of the cookbook not here :)

2019-01-07 20:09 UTC, damacus commented on resources/config.rb
> +  user new_resource.owner do
any resource 


without config in between the do end blocks can get rid of the do end blocks. 
e.g. 
```suggestion
  user new_resource.owner
```

2019-01-07 20:21 UTC, damacus requested changes

2019-01-07 20:21 UTC, damacus commented on spec/unit/default_spec.rb
> +platforms = {
For a better time testing custom resources look at https://github.com/sous-chefs/apache2/tree/master/spec/resources

2019-01-14 21:20 UTC, damacus commented on test/fixtures/cookbooks/test/recipes/install.rb
> +grafana_config 'Grafana' do
Fix me please

2019-01-15 09:04 UTC, damacus approved these changes

2019-01-15 10:15 UTC, merged