Grafana needs restart after plugins updated
sous-chefs/grafana pull request #265
Opened 2019-05-23 00:39 UTC by atward

Docs: https://grafana.com/docs/plugins/installation/
> after modifying plugins, grafana-server needs to be restarted.

There was an existing `plugins_spec.rb` that was unused. Added it to test suite.

2019-05-23 00:47 UTC, atward commented
Also blocked on #257 - as anonymous access is never configured until after the restart

```
     ×  status should eq 200
     
     expected: 200
          got: 401
```

2019-05-23 07:12 UTC, xorima requested changes

2019-05-23 07:12 UTC, Xorima commented on test/integration/plugins/plugins_spec.rb
> +  its(:stdout) { should include 'Version 6.2.0' }
Should we make this more generic, such as just look for 'Version' as otherwise it adds maintenance on us when upstream release anything?

2019-05-23 07:12 UTC, Xorima commented on kitchen.yml
> +  - name: plugins
in `.circleci/config.yml` could you add the following so the new tests run:
```
      - kitchen/dokken-single:
          name: plugins
          suite: plugins
          requires:
            *lint_and_unit
``` 
Thanks!

2019-06-14 12:14 UTC, xorima approved these changes

2019-06-14 12:14 UTC, merged