Extended logging/min_refresh_interval
sous-chefs/grafana pull request #363
Opened 2020-06-05 01:17 UTC by mbaitelman

# Description

Adds error message to failed calls

Adds support for min_refresh_interval  property 
https://grafana.com/docs/grafana/latest/installation/configuration/#min-refresh-interval
## Check List

- [ ] All tests pass. See TESTING.md for details.
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable.

2020-06-05 01:18 UTC, kitchen-porter commented
<!--
  1 Error: Please include a CHANGELOG ent...
  1 Warning: This Pull Request is probably ...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a CHANGELOG entry.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This Pull Request is probably missing tests.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2020-06-05 07:40 UTC, xorima requested changes
Hey,

Can you drop a test I'm for these changes, other than that they look fine 

Thanks mate

2020-06-06 09:09 UTC, xorima approved these changes

2020-06-06 09:09 UTC, merged

2020-06-06 09:14 UTC, Xorima commented
Released as 9.1.0